# Generated by Django 4.0.6 on 2022-09-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reviews',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.review'),
        ),
    ]
