# Generated by Django 4.0.6 on 2022-09-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='aaa', max_length=255),
            preserve_default=False,
        ),
    ]
