# Generated by Django 4.0.6 on 2022-10-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.CharField(default='blue', max_length=255),
            preserve_default=False,
        ),
    ]
