# Generated by Django 4.0.6 on 2022-10-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_item_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='info',
            field=models.JSONField(default={}),
        ),
    ]
