# Generated by Django 4.0.6 on 2022-09-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='password2',
        ),
    ]
