# Generated by Django 4.0.6 on 2022-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_shopuser_password1_remove_shopuser_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='cart',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='liked',
            field=models.JSONField(null=True),
        ),
    ]
