# Generated by Django 4.0.6 on 2022-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_shopuser_access_token_shopuser_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='refresh_token',
            field=models.CharField(max_length=255),
        ),
    ]
