# Generated by Django 4.0.6 on 2022-09-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cart_liked'),
        ('authentication', '0010_alter_shopuser_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cart'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='liked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.liked'),
        ),
    ]
