# Generated by Django 4.0.6 on 2022-09-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_shopuser_cart_alter_shopuser_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='cart',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='liked',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
