# Generated by Django 4.0.6 on 2022-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_shopuser_liked_shopuser_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='birth_date',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='gender',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='last_name',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
