# Generated by Django 4.0.6 on 2022-11-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_shopuser_birth_date_shopuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='last_name',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
