# Generated by Django 4.0.6 on 2022-11-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_shopuser_birth_date_alter_shopuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='phone_number',
        ),
    ]
